dist: xenial
env:
  global:
    GIT_BRANCH: "$TRAVIS_BRANCH" # Specify the branch name manually when on a detached HEAD
  matrix:
    - STACK=monitor
script:
  - if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_PULL_REQUEST" == false ]]; then ./stack deploy "$STACK"; fi
notifications:
  webhooks:
    urls: https://vbot.ghn.me/travis
  slack:
    secure: fM1+n5KxxRyCESxg297OusbWMUaxnJWB73dF3u7wy3WvOAEoIBMz5RmqNC+kjNip5GyEAMoMXQmkFRIembU3uQngo9ZGm5+dPvRpEasu6aAG6zLcbPoQnIJvzLftzq++6s5kpp+ZoXuvRKabr9yyrYWr00jXZBt7UGfb3k+W8h1b2giBQxiAoscA2ohq6bhnb2eJVLPnOqI7LzaD+KEv8Fk5Mfw4d6Qpq75waXbTjZLPi/OQ+UGIMV7OAtSMYCmnoqlo+Jh0MQaKF/VPnX53gf3ZESAfi0ejbIz3h7w29JjpKtE4Jxafa2/FtC2bkbYLDd+ROZWO5H1qWjsxnmMRW7AcKxzTKX9BPAhdMJYdX0RQ33x7mfjv2v6G97jocfRYGJbNa9E8cw7XuvZgcL3rr5mKfl7m0WKHjAO5DkXlfnKaaCyncgY+I9vctPwYShfGt484ypzGFpshNqV7b57HE7ymaF/xQ/v6diQ94T6V09MLFJWymBB3J58CpyWkVFY8MCAvHv5hIk67HATx8ZSIabigVP/+hQdteamZdnUzmqOUgxinNhXCFKb0hZP021gr7cNSDJ5wcOsfZblbFZvfVf6Lh53RHx8jMUVa82MXXHt2g0hQdXyLBH5YHonTFcLwmpN6vqJ9l0YDcsfMCDEPt4EOaXJTcPiBFPOu89KdpWk=
