dist: xenial
language: ruby
branches:
  except:
    - "/^v\\d/"
cache:
  directories:
    - vendor/bundle
env:
  PACKER_VERSION: '1.3.2'
  TF_VERSION: '0.11.8'
  SC_VERSION: 'stable' # or "v0.4.7", or "latest"
install:
  # Install a custom version of shellcheck instead of Travis CI's default
  - |
    wget "https://storage.googleapis.com/shellcheck/shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
    tar --xz -xvf "shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
    shellcheck() { "shellcheck-${SC_VERSION}/shellcheck" "$@"; }
    shellcheck --version
  # Install gems
  - bundle install --without development --path vendor/bundle
  # Install PIP packages
  - pip install --user --upgrade awscli aws-amicleaner future && aws --version && amicleaner --version
  # Install Hashicorp's packages
  - |
    curl -L -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
    unzip -d ~/bin packer.zip
    packer version
  - |
    curl -L -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
    unzip -d ~/bin terraform.zip
    terraform version
before_script: |
  if [[ ${TRAVIS_PULL_REQUEST:-false} == false ]]; then
    aws configure --profile ursa set region us-east-1
    aws configure --profile ursa set aws_access_key_id "${TRAVIS_AWS_ACCESS_KEY_ID}"
    aws configure --profile ursa set aws_secret_access_key "${TRAVIS_AWS_SECRET_ACCESS_KEY}"
    aws configure --profile orion set role_arn "${TRAVIS_ORION_ROLE_ARN}"
    aws configure --profile orion set source_profile ursa
  fi
jobs:
  include:
    - stage: "Tests"
      script: |
        find ./bin ./shlib -type f -exec shellcheck {} +
    - stage: "Images"
      if: branch = master AND type != pull_request
      script: |
        ./bin/stack ami validate prometheus
        ./bin/stack ami build prometheus
    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: |
        ./bin/stack tf init
        ./bin/stack tf validate
        ./bin/stack tf plan
        ./bin/stack tf apply -auto-approve
notifications:
  webhooks:
    urls: https://vbot.ghn.me/travis
  slack:
    secure: fM1+n5KxxRyCESxg297OusbWMUaxnJWB73dF3u7wy3WvOAEoIBMz5RmqNC+kjNip5GyEAMoMXQmkFRIembU3uQngo9ZGm5+dPvRpEasu6aAG6zLcbPoQnIJvzLftzq++6s5kpp+ZoXuvRKabr9yyrYWr00jXZBt7UGfb3k+W8h1b2giBQxiAoscA2ohq6bhnb2eJVLPnOqI7LzaD+KEv8Fk5Mfw4d6Qpq75waXbTjZLPi/OQ+UGIMV7OAtSMYCmnoqlo+Jh0MQaKF/VPnX53gf3ZESAfi0ejbIz3h7w29JjpKtE4Jxafa2/FtC2bkbYLDd+ROZWO5H1qWjsxnmMRW7AcKxzTKX9BPAhdMJYdX0RQ33x7mfjv2v6G97jocfRYGJbNa9E8cw7XuvZgcL3rr5mKfl7m0WKHjAO5DkXlfnKaaCyncgY+I9vctPwYShfGt484ypzGFpshNqV7b57HE7ymaF/xQ/v6diQ94T6V09MLFJWymBB3J58CpyWkVFY8MCAvHv5hIk67HATx8ZSIabigVP/+hQdteamZdnUzmqOUgxinNhXCFKb0hZP021gr7cNSDJ5wcOsfZblbFZvfVf6Lh53RHx8jMUVa82MXXHt2g0hQdXyLBH5YHonTFcLwmpN6vqJ9l0YDcsfMCDEPt4EOaXJTcPiBFPOu89KdpWk=
