dist: trusty
group: travis_latest
language: ruby
branches:
  except:
    - "/^v\\d/"
cache:
  directories:
    - vendor/bundle
env:
  PACKER_VERSION: '1.2.5'
  TF_VERSION: '0.11.8'
  SC_VERSION: 'stable' # or "v0.4.7", or "latest"
install:
  # Install a custom version of shellcheck instead of Travis CI's default
  - |
    wget "https://storage.googleapis.com/shellcheck/shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
    tar --xz -xvf "shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
    shellcheck() { "shellcheck-${SC_VERSION}/shellcheck" "$@"; }
    shellcheck --version
  # Install gems
  - bundle install --without development --path vendor/bundle
  # Install PIP packages
  - pip install --user --upgrade awscli aws-amicleaner future && aws --version && amicleaner --version
  # Install Hashicorp's packages
  - |
    curl -L -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
    unzip -d ~/bin packer.zip
    packer version
  - |
    curl -L -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
    unzip -d ~/bin terraform.zip
    terraform version
before_script: |
  if [[ ${TRAVIS_PULL_REQUEST:-false} == false ]]; then
    aws configure --profile ursa set region us-east-1
    aws configure --profile ursa set aws_access_key_id "${TRAVIS_AWS_ACCESS_KEY_ID}"
    aws configure --profile ursa set aws_secret_access_key "${TRAVIS_AWS_SECRET_ACCESS_KEY}"
    aws configure --profile orion set role_arn "${TRAVIS_ORION_ROLE_ARN}"
    aws configure --profile orion set source_profile ursa
  fi
jobs:
  include:
    - stage: "Tests"
      script: |
        find ./bin ./shlib -type f -exec shellcheck {} +
        ./bin/stack ami validate prometheus
    - stage: "Images"
      if: branch = master
      script: |
        ./bin/stack ami build prometheus
    - stage: "Deploy"
      if: branch = master
      script: |
        ./bin/stack tf init
        ./bin/stack tf validate
        ./bin/stack tf plan
        ./bin/stack tf apply -auto-approve
notifications:
  webhooks:
    urls: https://vbot.ghn.me/travis
  slack:
    secure: jJ3ZVC1hxVShU5PI9CtUuDB6sTxjjE0AnNAUMJmE2QqNMWztUOYrdHkcahYv8xi4ebPs78tb8d9zMSWQqyCCqcHdZFnfTd/TLpKu184C+Jh1fyu9asLe6rnHLwsDPFzQKz9cfGQK60JEWOrHJD4eJMB35U6W1UT+oTaWod4AR/tmbzkDg5jfcwfH9+DLor6iI2KmAcAHAUP/v6nL2pJBp5codwjwDXSmTV95xP60lguL6MQefz6Wh+0k+KtDZ1RX7omugd4rbCAGwji2m9oL+JbFW9ABERfLL6ohUiE7UJQpGo//vnbF+hox0xuTL73ZEPFVQ7/T3K6tyCrbVy9HxHjCKWivJXHGQY7wNPfIS7xRKG1FBv5kFyawXr//Yg/LvaGCQc0oYrUdwGh177yl/TH7g0nbZwPH0oFud2f340RB1DMTFIkxWGOuhC6LALln6yqbh0+STjN89xUIqUB7JBbl2QANUX1vFvNj8/FeDfTV4G+wMz40FJfb5ds+nKTOq1r03wuq8C1o5BdwxVc9L2KOsrKsQ7GQwmS8k2LQTKXIUNTpoOzvFG2kdFruM0pYafm9mCQYtUQogsy7ahPDbv0zlTq0P4EX5xbup8JjO3rQrBy80WTpLwZnEx+sgaSk9+tsDzfSXGc3b9x7DndktopUCEe0yK/aEn+cCY8T6TM=
