version: '3'

services:
  lb:
    image: dockercloud/haproxy:latest
    links:
      - api
      - server
    environment:
      CERT_FOLDER: '/var/secrets/ssl'
    ports:
      - '443:443'
      - '8140:8140'
    command: sh -c 'until ls -A /var/secrets/ssl >/dev/null 2>&1; do echo "Waiting for certificates"; sleep 5; done; sh -c "dockercloud-haproxy"'
    restart: unless-stopped
    volumes:
      - secrets:/var/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
      - backend
  api:
    image: vladgh/vpm-api:latest
    hostname: api
    environment:
      API_CONFIG: '/var/secrets/api.yml'
      SERVICE: 'secrets,r10k'
      VIRTUAL_HOST: 'https://*'
    entrypoint: sh -c 'until [ -s /var/secrets/api.yml ]; do echo "Waiting for configuration"; sleep 5; done; sh -c "bundle exec puma --environment $${RACK_ENV} --port $${RACK_PORT}"'
    restart: unless-stopped
    volumes:
      - secrets:/var/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
  server:
    image: vladgh/vpm-server:latest
    hostname: puppet.ghn.me
    environment:
      AUTOSIGN_CFG: '/var/secrets/csr.yml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me'
      JAVA_ARGS: '-Xms1G -Xmx1G'
      TCP_PORTS: '8140'
      entrypoint: sh -c 'until [ -s $${AUTOSIGN_CFG} ] && [ -s /etc/puppetlabs/code/environments/production/.r10k-deploy.json ]; do echo "Waiting for secrets and R10K"; sleep 5; done; /entrypoint.sh puppetserver foreground'
    restart: unless-stopped
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl
      - secrets:/var/secrets
      - code:/etc/puppetlabs/code
      - ~/.aws:/root/.aws:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
  ssl:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    environment:
      S3PATH: 's3://vladgh/ssl'
      WATCHDIR: '/etc/puppetlabs/puppet/ssl'
    restart: unless-stopped
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl
      - ~/.aws:/root/.aws:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
  secrets:
    image: vladgh/s3sync:latest
    hostname: secrets-sync-agent
    environment:
      S3PATH: 's3://vladgh/secrets'
      DESTINATION: '/var/secrets'
    volumes:
      - secrets:/var/secrets
      - ~/.aws:/root/.aws:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    environment:
      REMOTE: 'https://github.com/vghn/puppet.git'
    command: 'r10k deploy environment --puppetfile'
    volumes:
      - code:/etc/puppetlabs/code
      - /etc/localtime:/etc/localtime:ro
      - /var/cache/r10k
    networks:
      - backend
  log:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    command: syslog+tls://logs4.papertrailapp.com:11854
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

volumes:
  ssl:
  code:
  secrets:

networks:
  frontend:
  backend:
