version: '3.3'

services:
  lb:
    image: vladgh/lb:latest
    environment:
      CERT_FOLDER: '/certs'
      LIVE_CERT_FOLDER: '/etc/letsencrypt/live'
    ports:
      - '80:80'
      - '443:443'
      - '8140:8140'
      - mode: host
        target: 1936
        published: 1936
    volumes:
      - certs:/certs
      - letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - encrypted
      - puppet
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  webhook:
    image: vladgh/wh:latest
    hostname: webhook
    environment:
      API_CONFIG: '/run/secrets/webhook.yml'
      SERVICE_PORTS: '8523'
      FORCE_SSL: 'yes'
      VIRTUAL_HOST: 'http://*,https://*'
    secrets:
      - webhook.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - encrypted
    deploy:
      mode: global
  puppet:
    image: vladgh/ps:latest
    hostname: puppet.ghn.me
    environment:
      AUTOSIGN_CFG: '/run/secrets/puppet_csr.yml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me,puppetdb,puppetdb.ghn.me' # these will be reused by puppetdb
      PUPPETSERVER_JAVA_ARGS: '-Xms1024M -Xmx1024M'
      SERVICE_PORTS: '8140'
      TCP_PORTS: '8140'
    secrets:
      - eyaml_private_key.pkcs7.pem
      - eyaml_public_key.pkcs7.pem
      - puppet_csr.yml
      - source: aws_credentials_rhea
        target: /root/.aws/credentials
    entrypoint: /sbin/tini -- sh -c 'until [ -s /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem ] && [ -s /etc/puppetlabs/code/environments/production/.r10k-deploy.json ]; do echo "Waiting for R10K..."; sleep 5; done; /entrypoint.sh puppetserver foreground'
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
    networks:
      - puppet
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  puppetdb:
    image: vladgh/puppetdb:latest
    hostname: puppetdb.ghn.me
    labels:
      logspout.exclude: 'true'
    environment:
      PUPPETDB_CERTNAME: 'puppet.ghn.me'
      PUPPETDB_HOST: 'pdhmbnpv0r5lty.cwmrzqfvkzxh.us-east-1.rds.amazonaws.com'
      PUPPETDB_JAVA_ARGS: '-Xms512M -Xmx512M'
    secrets:
      - puppetdb_user
      - puppetdb_pass
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl:ro
    ports:
      - mode: host
        target: 8080
        published: 8080
    networks:
      - frontend
      - puppet
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  puppetboard:
    image: vladgh/puppetboard:latest
    hostname: puppetboard.ghn.me
    labels:
      logspout.exclude: 'true'
    ports:
      - mode: host
        target: 8000
        published: 8000
    networks:
      - frontend
      - puppet
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  letsencrypt:
    image: vladgh/le:latest
    hostname: letsencrypt-agent
    environment:
      SERVICE_PORTS: '80'
      VIRTUAL_HOST: '*/.well-known/acme-challenge/*'
      VIRTUAL_HOST_WEIGHT: '999'
      DOMAINS: 'rhea.ghn.me,puppet.ghn.me,puppetca.ghn.me'
      EMAIL: 'webmaster@ghn.me'
      LOAD_BALANCER_SERVICE_NAME: 'lb'
    volumes:
      - letsencrypt:/etc/letsencrypt
    networks:
      - encrypted
  ssl:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    environment:
      S3PATH: 's3://vgast/puppet/ssl'
    secrets:
      - source: aws_credentials_rhea
        target: /root/.aws/credentials
    command: sync
    volumes:
      - ssl:/sync
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    environment:
      REMOTE: 'https://github.com/vghn/puppet.git'
      CRON_TIME: '10 * * * *'
    command: 'r10k deploy environment --puppetfile'
    volumes:
      - code:/etc/puppetlabs/code
      - /var/cache/r10k
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  backup:
    image: vladgh/backup:latest
    hostname: backup-agent
    environment:
      AWS_S3_BUCKET: 'vgbak'
      AWS_S3_PREFIX: 'rhea'
      GPG_RECIPIENT: 'vlad@ghn.me'
      GPG_KEY_URL: 'https://keybase.io/vgh/key.asc'
    secrets:
      - source: aws_credentials_rhea
        target: /root/.aws/credentials
    command: cron
    volumes:
      - letsencrypt:/backup/letsencrypt               # LetsEncrypt Certificates
      - ssl:/backup/puppet-ca                         # PuppetCA Certificates
      - /etc/puppetlabs/puppet/ssl:/backup/puppet-ssl # Puppet Agent Certificates
      - /var/lib/docker/swarm:/backup/swarm           # Swarm state
    networks:
      - backend
    deploy:
      mode: global
  log:
    image: gliderlabs/logspout:v3.2.2
    hostname: log-agent
    environment:
      BACKLOG: 'false'
      EXCLUDE_LABEL: 'logspout.exclude'
    command: syslog+tls://logs4.papertrailapp.com:11854
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    deploy:
      mode: global

secrets:
  aws_credentials_rhea:
    external: true
  eyaml_private_key.pkcs7.pem:
    external: true
  eyaml_public_key.pkcs7.pem:
    external: true
  puppet_csr.yml:
    external: true
  puppetdb_pass:
    external: true
  puppetdb_user:
    external: true
  webhook.yml:
    external: true

volumes:
  ssl:
    driver: local
  code:
    driver: local
  certs:
    driver: local
  letsencrypt:
    driver: local

networks:
  frontend:
  encrypted:
    driver: overlay
    driver_opts:
      encrypted: ""
  puppet:
    driver: overlay
    driver_opts:
      encrypted: ""
  backend:
    driver: overlay
    driver_opts:
      encrypted: ""
