version: '3.3'

services:
  lb:
    image: traefik:1.3-alpine
    hostname: lb
    command: >-
      --configfile=/dev/null
      --web --web.address="0.0.0.0:8888"
      --docker --docker.swarmmode --docker.domain=traefik --docker.watch
      --defaultentrypoints='http,https'
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --acme --acme.email='webmaster@ghn.me' --acme.domains='rhea.ghn.me,puppet.ghn.me,puppetca.ghn.me' --acme.entryPoint=https --acme.storage=/certs/acme.json
    ports:
      - '80:80'
      - '443:443'
      - mode: host
        target: 8888
        published: 8888
    volumes:
      - certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - encrypted
    deploy:
      placement:
        constraints:
          - node.role == manager
  webhook:
    image: vladgh/wh:latest
    hostname: webhook
    environment:
      API_CONFIG: '/run/secrets/webhook.yml'
    secrets:
      - webhook.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - encrypted
    deploy:
      labels:
        - "traefik.tags=webhook"
        - "traefik.port=8523"
        - "traefik.frontend.rule=HostRegexp:{subdomain:[a-zA-Z0-9]+}.ghn.me"
      placement:
        constraints:
          - node.labels.role == rhea
  puppet:
    image: vladgh/ps:latest
    hostname: puppet.ghn.me
    environment:
      AUTOSIGN_CFG: '/run/secrets/puppet_csr.yml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me,puppetdb,puppetdb.ghn.me' # these will be reused by puppetdb
      PUPPETSERVER_JAVA_ARGS: '-Xms128M -Xmx768M'
    secrets:
      - source: eyaml_private_key.pkcs7.pem
        target: /etc/puppetlabs/puppet/eyaml/eyaml_private_key.pkcs7.pem
      - source: eyaml_public_key.pkcs7.pem
        target: /etc/puppetlabs/puppet/eyaml/eyaml_public_key.pkcs7.pem
      - source: aws_credentials_rhea
        target: /root/.aws/credentials
      - puppet_csr.yml
    entrypoint: /sbin/tini -- sh -c 'until [ -s /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem ] && [ -s /etc/puppetlabs/code/environments/production/.r10k-deploy.json ]; do echo "Waiting for R10K..."; sleep 5; done; /entrypoint.sh puppetserver foreground'
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
    ports:
      - mode: host
        target: 8140
        published: 8140
    networks:
      - puppet
    deploy:
      resources:
        limits:
          memory: 768M
      placement:
        constraints:
          - node.labels.role == rhea
  puppetdb:
    image: vladgh/puppetdb:latest
    hostname: puppetdb.ghn.me
    labels:
      logspout.exclude: 'true'
    environment:
      PUPPETDB_CERTNAME: 'puppet.ghn.me'
      PUPPETDB_HOST: 'pdhmbnpv0r5lty.cwmrzqfvkzxh.us-east-1.rds.amazonaws.com'
      PUPPETDB_JAVA_ARGS: '-Xms128M -Xmx768M'
    secrets:
      - puppetdb_user
      - puppetdb_pass
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl:ro
    ports:
      - mode: host
        target: 8080
        published: 8080
    networks:
      - puppet
    deploy:
      resources:
        limits:
          memory: 768M
      placement:
        constraints:
          - node.labels.role == rhea
  puppetboard:
    image: vladgh/puppetboard:latest
    hostname: puppetboard.ghn.me
    labels:
      logspout.exclude: 'true'
    ports:
      - mode: host
        target: 8000
        published: 8000
    networks:
      - puppet
    deploy:
      resources:
        limits:
          memory: 64M
      placement:
        constraints:
          - node.labels.role == rhea
  ssl:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    environment:
      S3PATH: 's3://vgast/puppet/ssl'
    secrets:
      - source: aws_credentials_rhea
        target: /root/.aws/credentials
    command: sync
    volumes:
      - ssl:/sync
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    labels:
      r10k: 'true'
    environment:
      REMOTE: 'https://github.com/vghn/puppet.git'
      CRON_TIME: '10 * * * *'
    command: 'r10k deploy environment --puppetfile'
    volumes:
      - code:/etc/puppetlabs/code
      - /var/cache/r10k
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  backup:
    image: vladgh/backup:latest
    hostname: backup-agent
    environment:
      AWS_S3_BUCKET: 'vgbak'
      AWS_S3_PREFIX: 'rhea'
      GPG_RECIPIENT: 'vlad@ghn.me'
      GPG_KEY_URL: 'https://keybase.io/vgh/key.asc'
    secrets:
      - source: aws_credentials_rhea
        target: /root/.aws/credentials
    command: cron
    volumes:
      - certs:/backup/certs                           # LetsEncrypt Certificates
      - ssl:/backup/puppet-ca                         # PuppetCA Certificates
      - /etc/puppetlabs/puppet/ssl:/backup/puppet-ssl # Puppet Agent Certificates
      - /var/lib/docker/swarm:/backup/swarm           # Swarm state
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.labels.role == rhea
  log:
    image: gliderlabs/logspout:v3.2.2
    hostname: log-agent
    environment:
      BACKLOG: 'false'
      EXCLUDE_LABEL: 'logspout.exclude'
    command: syslog+tls://logs4.papertrailapp.com:11854
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    deploy:
      mode: global

secrets:
  aws_credentials_rhea:
    external: true
  eyaml_private_key.pkcs7.pem:
    external: true
  eyaml_public_key.pkcs7.pem:
    external: true
  puppet_csr.yml:
    external: true
  puppetdb_pass:
    external: true
  puppetdb_user:
    external: true
  webhook.yml:
    external: true

volumes:
  ssl:
    driver: local
  code:
    driver: local
  certs:
    driver: local

networks:
  frontend:
  encrypted:
    driver: overlay
    driver_opts:
      encrypted: ""
  puppet:
    driver: overlay
    driver_opts:
      encrypted: ""
  backend:
    driver: overlay
    driver_opts:
      encrypted: ""
