version: '3'

services:
  lb:
    image: vladgh/lb:latest
    environment:
      CERT_FOLDER: '/certs'
      LIVE_CERT_FOLDER: '/etc/letsencrypt/live'
      STATS_PORT: '1936'
    ports:
      - '80:80'
      - '443:443'
      - '8140:8140'
      - '8080:8080'
      - '8000:8000'
      - '1936:1936'
    entrypoint: /sbin/tini -- sh -c 'until [ -s /var/secrets/haproxy_credentials ]; do echo "Waiting for credentials..."; sleep 5; done; set -o allexport; . /var/secrets/haproxy_credentials; set +o allexport; /entrypoint.sh dockercloud-haproxy'
    volumes:
      - certs:/certs
      - letsencrypt:/etc/letsencrypt
      - secrets:/var/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - encrypted
      - puppet
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
  webhook:
    image: vladgh/wh:latest
    hostname: webhook
    environment:
      API_CONFIG: '/var/secrets/webhook.yml'
      SERVICES: 'secrets,r10k'
      SERVICE_PORTS: '80'
      FORCE_SSL: 'yes'
      VIRTUAL_HOST: 'http://*,https://*'
    entrypoint: /sbin/tini -- sh -c 'until [ -s /var/secrets/webhook.yml ]; do echo "Waiting for configuration..."; sleep 5; done; sh -c "bundle exec puma --environment $${RACK_ENV} --port $${RACK_PORT}"'
    volumes:
      - secrets:/var/secrets:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  puppet:
    image: vladgh/ps:latest
    hostname: puppet.ghn.me
    environment:
      AUTOSIGN_CFG: '/var/secrets/csr.yml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me,puppetdb,puppetdb.ghn.me' # these will be reused by puppetdb
      PUPPETSERVER_JAVA_ARGS: '-Xms32M -Xmx512M'
      SERVICE_PORTS: '8140'
      TCP_PORTS: '8140'
    entrypoint: /sbin/tini -- sh -c 'until [ -s $${AUTOSIGN_CFG} ] && [ -s /etc/puppetlabs/code/environments/production/.r10k-deploy.json ]; do echo "Waiting for secrets and R10K..."; sleep 5; done; /entrypoint.sh puppetserver foreground'
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl
      - secrets:/var/secrets:ro
      - code:/etc/puppetlabs/code
      - ~/.aws:/root/.aws:ro
    networks:
      - puppet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  puppetdb:
    image: vladgh/puppetdb:latest
    hostname: puppetdb.ghn.me
    environment:
      SERVICE_PORTS: '8080'
      PUPPETDB_JAVA_ARGS: '-Xms32M -Xmx128M'
    entrypoint: /sbin/tini -- sh -c 'until [ -s /var/secrets/puppetdb_credentials ]; do echo "Waiting for credentials..."; sleep 5; done; set -o allexport; . /var/secrets/puppetdb_credentials; set +o allexport; puppet config set certname puppet.ghn.me --section main && /entrypoint.sh puppetdb foreground'
    volumes:
      - ssl:/etc/puppetlabs/puppet/ssl:ro
      - secrets:/var/secrets:ro
    networks:
      - puppet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  puppetboard:
    image: vladgh/puppetboard:latest
    hostname: puppetboard.ghn.me
    environment:
      SERVICE_PORTS: '8000'
    networks:
      - puppet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  letsencrypt:
    image: vladgh/le:latest
    hostname: letsencrypt-agent
    environment:
      SERVICE_PORTS: '80'
      VIRTUAL_HOST: '*/.well-known/acme-challenge/*'
      VIRTUAL_HOST_WEIGHT: '999'
      DOMAINS: 'rhea.ghn.me,puppet.ghn.me,puppetca.ghn.me'
      EMAIL: 'webmaster@ghn.me'
      LOAD_BALANCER_SERVICE_NAME: 'lb'
    volumes:
      - letsencrypt:/etc/letsencrypt
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  ssl:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    environment:
      S3PATH: 's3://vgast/puppet/ssl'
    command: sync
    volumes:
      - ssl:/sync
      - ~/.aws:/root/.aws:ro
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  secrets:
    image: vladgh/s3sync:latest
    hostname: secrets-sync-agent
    environment:
      S3PATH: 's3://vgsec'
      INITIAL_DOWNLOAD: 'force'
    command: periodic_download
    volumes:
      - secrets:/sync
      - ~/.aws:/root/.aws:ro
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    environment:
      REMOTE: 'https://github.com/vghn/puppet.git'
      CRON_TIME: '10 * * * *'
    command: 'r10k deploy environment --puppetfile'
    volumes:
      - code:/etc/puppetlabs/code
      - /var/cache/r10k
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  log:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    command: syslog+tls://logs4.papertrailapp.com:11854
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  backup:
    image: vladgh/backup:latest
    hostname: backup-agent
    environment:
      AWS_S3_BUCKET: 'vgbak'
      AWS_S3_PREFIX: 'rhea'
      GPG_RECIPIENT: 'vlad@ghn.me'
      GPG_KEY_URL: 'https://keybase.io/vgh/key.asc'
    command: cron
    volumes:
      - ssl:/backup/puppetca
      - letsencrypt:/backup/letsencrypt
      - ~/.aws:/root/.aws:ro
    networks:
      - encrypted
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  ssl:
    driver: local
  code:
    driver: local
  certs:
    driver: local
  letsencrypt:
    driver: local
  secrets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=100m,nodev,nosuid"

networks:
  frontend:
    driver: overlay
    driver_opts:
      encrypted: ""
  encrypted:
    driver: overlay
    driver_opts:
      encrypted: ""
  puppet:
    driver: overlay
    driver_opts:
      encrypted: ""
