global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 10s
  external_labels:
    monitor: vgh

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

rule_files:
  - alertrules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          alias: Prometheus
          node: Prometheus
  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000
        labels:
          alias: Grafana
          node: Prometheus
  - job_name: nodes
    static_configs:
      - targets:
          - prometheus.ghn.me:9100
        labels:
          node: Prometheus
          group: vgh
      - targets:
          - vault.ghn.me:9100
        labels:
          node: Vault
          group: vgh
      - targets:
          - home.ghn.me:9101
        labels:
          node: VDev
          group: vgh.local
      - targets:
          - home.ghn.me:9102
        labels:
          node: VDS
          group: vgh.local
      - targets:
          - home.ghn.me:9103
        labels:
          node: VBS
          group: vgh.local
      - targets:
          - home.ghn.me:9104
        labels:
          node: VPH
          group: vgh.local
      - targets:
          - home.ghn.me:9105
        labels:
          node: VMS
          group: vgh.local
  - job_name: containers
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          node: Prometheus
          group: vgh
