Description: VGH Billing Alarms

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  MaxMonthlyExpenseInDollars:
    Type: Number
    Description: >
      The maximum dollars to spend in the account per month before an
      alarm is triggered.
    Default: 10
  RecipientEmailAddress:
    Type: String
    Description: >
      The email recipient for all billing alarms.

Resources:
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingTopic
      AlarmDescription: >
        Alarm for billing overusage of this account.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: "AWS/Billing"
      OKActions:
        - !Ref AlertingTopic
      Period: 21600 # 6 hours
      Statistic: Maximum
      Threshold: !Ref MaxMonthlyExpenseInDollars

  AlertingTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Billing Alerts
      Subscription:
        - Protocol: email
          Endpoint: !Ref RecipientEmailAddress
