Description: VGH Billing Alarms

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  RecipientEmailAddress:
    Type: String
    Description: >
      The email recipient for all billing alarms.
  AlarmThresholds:
    Type: CommaDelimitedList
    Description: >
      Numerical Thresholds - in $USD - for Billing alarms
      Enter five (5) values for the billing alarms (e.g., 1,5,10,20,50)

Resources:
  BillingAlertOne:
    Type: AWS::CloudWatch::Alarm
    DependsOn: AlertingTopic
    Properties:
      AlarmActions:
        - !Ref AlertingTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [0, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [0, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [0, !Ref AlarmThresholds]

  BillingAlertTwo:
    Type: AWS::CloudWatch::Alarm
    DependsOn: AlertingTopic
    Properties:
      AlarmActions:
        - !Ref AlertingTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [1, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [1, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [1, !Ref AlarmThresholds]

  BillingAlertThree:
    Type: AWS::CloudWatch::Alarm
    DependsOn: AlertingTopic
    Properties:
      AlarmActions:
        - !Ref AlertingTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [2, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [2, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [2, !Ref AlarmThresholds]

  BillingAlertFour:
    Type: AWS::CloudWatch::Alarm
    DependsOn: AlertingTopic
    Properties:
      AlarmActions:
        - !Ref AlertingTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [3, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [3, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [3, !Ref AlarmThresholds]

  BillingAlertFive:
    Type: AWS::CloudWatch::Alarm
    DependsOn: AlertingTopic
    Properties:
      AlarmActions:
        - !Ref AlertingTopic
      AlarmDescription: !Join ["", ["Account Billing Alert for $", !Select [4, !Ref AlarmThresholds], ".00"]]
      AlarmName: !Join ["", ["Billing Alert - Estimated Bill Exceeds $", !Select [4, !Ref AlarmThresholds]]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600
      Statistic: Maximum
      Threshold: !Select [4, !Ref AlarmThresholds]

  AlertingTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Billing Alerts
      Subscription:
        - Protocol: email
          Endpoint: !Ref RecipientEmailAddress
