Description: VGH EFS

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  NumberOfAZs:
    AllowedValues:
      - '2'
      - '3'
      - '4'
    Default: '2'
    Description: Number of Availability Zones to use in the VPC. This must match the
      number of zones in existing in the region.
    Type: String
  SecurityGroupIDs:
    Description: The list of security group ids
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIDs:
    Description: The list of subnet ids
    Type: List<AWS::EC2::Subnet::Id>
  VolumeName:
    Default: EFS
    Description: The name to be used for the EFS volume
    Type: String

Conditions:
  3AZCondition: !Or [ !Equals [!Ref NumberOfAZs, "3" ], Condition: 4AZCondition ]
  4AZCondition: !Equals [!Ref NumberOfAZs, "4"]

Resources:
  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Ref VolumeName
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: !Ref SecurityGroupIDs
      SubnetId: !Select ['0',  !Ref SubnetIDs]
  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: !Ref SecurityGroupIDs
      SubnetId: !Select ['1', !Ref SubnetIDs]
  MountTarget3:
    Type: AWS::EFS::MountTarget
    Condition: 3AZCondition
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: !Ref SecurityGroupIDs
      SubnetId: !Select ['2', !Ref SubnetIDs]
  MountTarget4:
    Type: AWS::EFS::MountTarget
    Condition: 4AZCondition
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: !Ref SecurityGroupIDs
      SubnetId: !Select ['3', !Ref SubnetIDs]

Outputs:
  MountTarget1:
    Description: 1st Mount target ID
    Value: !Ref MountTarget1
  MountTarget2:
    Description: 2nd Mount target ID
    Value: !Ref MountTarget2
  MountTarget3:
    Condition: 3AZCondition
    Description: 3rd Mount target ID
    Value: !Ref MountTarget3
  MountTarget4:
    Condition: 4AZCondition
    Description: 4th Mount target ID
    Value: !Ref MountTarget4
  VolumeID:
    Description: The ID of the EFS volume
    Value: !Ref EFS
