Description: VGH ELB

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  SSLCertificateId:
    Description: The ARN of the SSL certificate to use
    Type: String
  SecurityGroupIDs:
    Description: The list of security group ids
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIDs:
    Description: The list of subnet ids
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ELB:
    Properties:
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '60'
      CrossZone: 'true'
      HealthCheck:
        HealthyThreshold: '2'
        Interval: '10'
        Target: TCP:8140
        Timeout: '5'
        UnhealthyThreshold: '6'
      Listeners:
      - InstancePort: '80'
        InstanceProtocol: HTTP
        LoadBalancerPort: '443'
        Protocol: HTTPS
        SSLCertificateId: !Ref SSLCertificateId
      - InstancePort: '8140'
        InstanceProtocol: TCP
        LoadBalancerPort: '8140'
        Protocol: TCP
      SecurityGroups: !Ref SecurityGroupIDs
      Subnets: !Ref SubnetIDs
    Type: AWS::ElasticLoadBalancing::LoadBalancer

Outputs:
  LoadBalancerURL:
    Description: URL - The Load Balancer Public DNS
    Value: !Join ['', ['https://', !GetAtt ELB.DNSName]]
