Description: VGH

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  AssetsBucketName:
    Description: The S3 bucket containing the assets
    Type: String
  BackupBucketName:
    Description: The S3 bucket containing the backups
    Type: String
  SecretsBucketName:
    Description: The S3 bucket containing the secrets
    Type: String
  MiniUserName:
    Description: Mini user name
    Type: String
    Default: mini
  PrometheusUserName:
    Description: Prometheus user name
    Type: String
    Default: prometheus
  PrometheusInstanceRoleArn:
    Description: Prometheus Instance Role ARN
    Type: String
  RheaUserName:
    Description: Rhea user name
    Type: String
    Default: rhea

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref AssetsBucketName
  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: AssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DenyUnEncryptedInflightOperations
          Effect: Deny
          Principal: '*'
          Action: s3:*
          Resource: !Join ['', ['arn:aws:s3:::', !Ref AssetsBucketName, '/*']]
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: AllowListing
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt [RheaUser, Arn]
          Action:
          - s3:ListBucket
          Resource: !Join ['', ['arn:aws:s3:::', !Ref AssetsBucketName]]
        - Sid: AlowRhea
          Effect: Allow
          Principal:
            AWS: !GetAtt [RheaUser, Arn]
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref AssetsBucketName, '/*']]
  BackupBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref BackupBucketName
      LifecycleConfiguration:
        Rules:
        - Id: Mini Hourly Rotation
          Prefix: mini/hourly/
          Status: Enabled
          ExpirationInDays: '1'
        - Id: Mini Daily Rotation
          Prefix: mini/daily/
          Status: Enabled
          ExpirationInDays: '7'
        - Id: Mini Weekly Rotation
          Prefix: mini/weekly/
          Status: Enabled
          ExpirationInDays: '30'
        - Id: Prometheus Hourly Rotation
          Prefix: prometheus/hourly/
          Status: Enabled
          ExpirationInDays: '1'
        - Id: Prometheus Daily Rotation
          Prefix: prometheus/daily/
          Status: Enabled
          ExpirationInDays: '7'
        - Id: Prometheus Weekly Rotation
          Prefix: prometheus/weekly/
          Status: Enabled
          ExpirationInDays: '30'
        - Id: Rhea Hourly Rotation
          Prefix: rhea/hourly/
          Status: Enabled
          ExpirationInDays: '1'
        - Id: Rhea Daily Rotation
          Prefix: rhea/daily/
          Status: Enabled
          ExpirationInDays: '7'
        - Id: Rhea Weekly Rotation
          Prefix: rhea/weekly/
          Status: Enabled
          ExpirationInDays: '30'
  BackupBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: BackupBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DenyUnEncryptedInflightOperations
          Effect: Deny
          Principal: '*'
          Action: s3:*
          Resource: !Join ['', ['arn:aws:s3:::', !Ref BackupBucketName, '/*']]
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: AllowListing
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt [MiniUser, Arn]
            - !GetAtt [RheaUser, Arn]
            - !Ref PrometheusInstanceRoleArn
          Action:
          - s3:ListBucket
          Resource: !Join ['', ['arn:aws:s3:::', !Ref BackupBucketName]]
        - Sid: AlowMini
          Effect: Allow
          Principal:
            AWS: !GetAtt [MiniUser, Arn]
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref BackupBucketName, '/mini/*']]
        - Sid: AlowPrometheus
          Effect: Allow
          Principal:
            AWS: !Ref PrometheusInstanceRoleArn
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref BackupBucketName, '/prometheus/*']]
        - Sid: AlowRhea
          Effect: Allow
          Principal:
            AWS: !GetAtt [RheaUser, Arn]
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref BackupBucketName, '/rhea/*']]
  SecretsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref SecretsBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  SecretsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: SecretsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DenyUnEncryptedInflightOperations
          Effect: Deny
          Principal: '*'
          Action: s3:*
          Resource: !Join ['', ['arn:aws:s3:::', !Ref SecretsBucketName, '/*']]
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: AllowListing
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt [RheaUser, Arn]
          Action:
          - s3:ListBucket
          Resource: !Join ['', ['arn:aws:s3:::', !Ref SecretsBucketName]]
        - Sid: AlowReadOnlyAccesstoSecrets
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt [RheaUser, Arn]
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref SecretsBucketName, '/*']]
        - Sid: DenyUnEncryptedObjectUploads
          Effect: Deny
          Principal: '*'
          Action:
          - s3:PutObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref SecretsBucketName, '/*']]
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: AES256

  OnPremiseGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: OnPremise

  MiniUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref MiniUserName
      Groups:
      - !Ref OnPremiseGroup
      Policies:
      - PolicyName: MiniUserPolicies
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - ssm:Get*
            Effect: Allow
            Resource: arn:aws:ssm:*:*:parameter/mini/*
            Sid: AllowGettingParameters
  MiniAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref MiniUser
  PrometheusUser:
    # Used by Grafana Billing Dashboard
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref PrometheusUserName
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
  PrometheusAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref PrometheusUser
  RheaUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref RheaUserName
      Groups:
      - !Ref OnPremiseGroup
      Policies:
      - PolicyName: RheaUserPolicies
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - ssm:Get*
            Effect: Allow
            Resource: arn:aws:ssm:*:*:parameter/rhea/*
            Sid: AllowGettingParameters
  RheaAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref RheaUser

Outputs:
  MiniAccessKey:
    Description: The Mini User Access Key
    Value: !Ref MiniAccessKey
  MiniSecretKey:
    Description: The Mini User Secret Key
    Value: !GetAtt MiniAccessKey.SecretAccessKey
  PrometheusAccessKey:
    Description: The Prometheus User Access Key
    Value: !Ref PrometheusAccessKey
  PrometheusSecretKey:
    Description: The Prometheus User Secret Key
    Value: !GetAtt PrometheusAccessKey.SecretAccessKey
  RheaAccessKey:
    Description: The Rhea User Access Key
    Value: !Ref RheaAccessKey
  RheaSecretKey:
    Description: The Rhea User Secret Key
    Value: !GetAtt RheaAccessKey.SecretAccessKey
