global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 10s
  external_labels:
    monitor: 'vgh'

rule_files:
  - 'alertrules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
        labels:
          alias: Prometheus
          node: Prometheus
  - job_name: 'grafana'
    static_configs:
      - targets:
          - 'grafana:3000'
        labels:
          alias: Grafana
          node: Prometheus
  - job_name: 'nodes'
    static_configs:
      - targets:
          - 'prometheus.ghn.me:9100'
        labels:
          node: Prometheus
      - targets:
          - 'rhea.ghn.me:9100'
        labels:
          node: Rhea
  - job_name: 'containers'
    static_configs:
      - targets:
          - 'cadvisor:8080'
        labels:
          node: Prometheus
      - targets:
          - 'rhea.ghn.me:9101'
        labels:
          node: Rhea

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
