Description: PuppetDB SG

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  TrustedIPs:
    Description: The IP address ranges that can be trusted
    Type: CommaDelimitedList
  VPCId:
    Description: The VPC ID
    Type: AWS::EC2::VPC::Id

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PuppetDB RDS Firewall
      VpcId: !Ref VPCId
  SecurityGroupAllowTrustedIPs1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt SecurityGroup.GroupId
      FromPort: '5432'
      ToPort: '5432'
      IpProtocol: tcp
      CidrIp: !Select ['0', !Ref TrustedIPs]
  SecurityGroupAllowTrustedIPs2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt SecurityGroup.GroupId
      FromPort: '5432'
      ToPort: '5432'
      IpProtocol: tcp
      CidrIp: !Select ['1', !Ref TrustedIPs]

Outputs:
  SecurityGroup:
    Description: The PuppetDB security group
    Value: !Ref SecurityGroup
