Description: Prometheus

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  IamInstanceProfile:
    Description: The instance profile
    Type: String
  ImageID:
    Description: The base image id
    Type: AWS::EC2::Image::Id
  InstanceType:
    Default: t2.micro
    Description: The instance type for the EC2 instance
    Type: String
  KeyName:
    Description: The name of the key pair used to log into the EC2 instance via SSH
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupIDs:
    Description: The list of security group ids
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIDs:
    Description: The list of subnet ids
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref Instance
      Domain: vpc

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIDs
      SubnetId: !Select ['0',  !Ref SubnetIDs]
      IamInstanceProfile: !Ref IamInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          set -euo pipefail
          IFS=$'\n\t'

          echo 'Update APT'
          while ! apt-get -qy update; do echo 'Waiting for APT'; sleep 1; done

          echo 'Ensure Python PIP is installed and updated'
          command -v pip >/dev/null 2>&1 || apt-get -qy install python-pip
          pip install --upgrade pip setuptools

          echo 'Ensure CloudFormation helper scripts are installed'
          [[ -x /usr/local/bin/cfn-init ]] || pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

          echo 'Ensure AWSCLI is installed'
          [[ -x /usr/local/bin/aws ]] || pip install --upgrade awscli

          echo 'Install Docker CE'
          curl -fsSL get.docker.com | sudo sh
          usermod -aG docker ubuntu

          echo 'Install Docker Compose'
          curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

Outputs:
  PublicIP:
    Description: The public IP
    Value: !GetAtt Instance.PublicIp
  PublicDnsName:
    Description: The public DNS
    Value: !GetAtt Instance.PublicDnsName
