Description: Prometheus

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String
  IamInstanceProfile:
    Description: The instance profile
    Type: String
  ImageID:
    Description: The base image id
    Type: AWS::EC2::Image::Id
  InstanceType:
    Default: t2.micro
    Description: The instance type for the EC2 instance
    Type: String
  KeyName:
    Description: The name of the key pair used to log into the EC2 instance via SSH
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupIDs:
    Description: The list of security group ids
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIDs:
    Description: The list of subnet ids
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Instance
      Domain: vpc

  Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 10
      VolumeType: gp2
      AvailabilityZone: !GetAtt Instance.AvailabilityZone
      Tags:
        - Key: Name
          Value: Prometheus

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref Instance
      VolumeId: !Ref Volume
      Device: /dev/sdg

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIDs
      SubnetId: !Select ['0',  !Ref SubnetIDs]
      IamInstanceProfile: !Ref IamInstanceProfile
      Tags:
        - Key: Name
          Value: Prometheus
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          set -euo pipefail
          IFS=$'\n\t'

          set -x
          export DEBIAN_FRONTEND=noninteractive

          echo 'Update APT'
          while ! apt-get -y update; do echo 'Waiting for APT' ; sleep 1; done

          # Upgrade system
          apt-get -qy dist-upgrade
          apt-get -qy autoremove --purge

Outputs:
  PublicIP:
    Description: The public IP
    Value: !GetAtt Instance.PublicIp
  PublicDnsName:
    Description: The public DNS
    Value: !GetAtt Instance.PublicDnsName
