Description: VGH MEC7 IAM

Parameters:
  EnvType:
    Default: production
    Description: The environment type
    Type: String

Resources:
  UnifiInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - !Ref UnifiInstanceRole
      Path: /
  UnifiInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
      Policies:
      - PolicyName: InstancePolicies
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - ec2:Describe*
            - autoscaling:Describe*
            - autoscaling:EnterStandby
            - autoscaling:ExitStandby
            - elasticloadbalancing:ConfigureHealthCheck
            - elasticloadbalancing:DescribeLoadBalancers
            Effect: Allow
            Resource: '*'
            Sid: AllowScalingOperations
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
            - arn:aws:logs:*:*:*
            Sid: AllowLogging

Outputs:
  UnifiInstanceProfile:
    Description: The Instance Profile
    Value: !Ref UnifiInstanceProfile
  UnifiInstanceRole:
    Description: The instance role name
    Value: !Ref UnifiInstanceRole
